#!/usr/bin/env python3
# -*- coding: utf-8 -*-
########################################################################
# Filename    : car_calibration.py
# Description : Car calibration and component testing
# Author      : Generated by AI Assistant
# Modification: 2026/01/05
########################################################################
"""
Steering Calibration

Calibrate the steering center position for your car.

Usage:
python3 car_calibration.py
"""

import json
import logging
import time
from lib.movement import CarControl

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class CarCalibrator:
    def __init__(self):
        self.car = CarControl()
        logger.info("Steering calibration system initialized")

    def calibrate_steering_center(self):
        """Calibrate the steering center position"""
        print("\n=== STEERING CENTER CALIBRATION ===")
        print("This will help set the correct center position for your steering servo.")
        print("Make sure your steering hardware is physically centered first.")
        print("\nInstructions:")
        print("1. Physically center your steering (straight ahead)")
        print("2. Use the controls below to find the correct center angle")
        print("3. When satisfied, save the configuration")
        print("\nControls:")
        print("  [angle] - Set steering angle (0-180)")
        print("  c - Center steering")
        print("  s - Save current position as center")
        print("  q - Quit without saving")

        while True:
            try:
                cmd = input(f"\nCurrent steering angle: {self.car.get_steering()}° > ").lower().strip()

                if cmd.isdigit():
                    angle = int(cmd)
                    if 0 <= angle <= 180:
                        self.car.set_steering(angle)
                        print(f"Steering set to {angle}°")
                    else:
                        print("Angle must be 0-180")
                elif cmd == 'c':
                    self.car.center_steering()
                    print(f"Steering centered to {self.car.get_steering()}°")
                elif cmd == 's':
                    current_angle = self.car.get_steering()
                    if input(f"\nSave {current_angle}° as the new steering center? (y/n): ").lower().strip() == 'y':
                        return self.save_steering_center(current_angle)
                    else:
                        print("Save cancelled.")
                elif cmd == 'q':
                    print("Calibration cancelled.")
                    return False
                else:
                    print("Invalid command. Use number, c, s, or q.")

            except KeyboardInterrupt:
                print("\nCalibration interrupted.")
                return False

    def reset_to_defaults(self):
        """Reset steering to default state"""
        self.car.center_steering()

    def save_steering_center(self, center_angle):
        """Save the steering center angle to config.json"""
        try:
            # Update steering center angle
            self.car.config["car_settings"]["steering"]["center_angle"] = center_angle

            # Save to file
            with open("config.json", 'w') as f:
                json.dump(self.car.config, f, indent=2)

            logger.info(f"Steering center saved to config.json: {center_angle}°")
            print(f"✓ Steering center saved: {center_angle}°")
            print("The car will now use this as the center position for steering.")
            return True

        except Exception as e:
            logger.error(f"Failed to save steering center: {e}")
            print(f"✗ Failed to save steering center: {e}")
            return False

    def run(self):
        """Main run method - simplified steering calibration only"""
        print("=== STEERING CALIBRATION ===")
        print("Calibrate your car's steering center position")

        success = self.calibrate_steering_center()

        if success:
            print("\n✓ Steering calibration completed successfully!")
        else:
            print("\n✗ Steering calibration was cancelled or failed.")

def main():
    """Main function"""
    calibrator = CarCalibrator()
    try:
        calibrator.run()
    except Exception as e:
        logger.error(f"Calibration failed: {e}")
    finally:
        # Ensure car is in safe state
        calibrator.reset_to_defaults()

if __name__ == '__main__':
    main()
