#!/usr/bin/env python3
# -*- coding: utf-8 -*-
########################################################################
# Filename    : demo_movement.py
# Description : Demo script to move car forward and backward for 4 seconds each
# Author      : Generated by AI Assistant
# Modification: 2026/01/04
########################################################################
"""
Demo Movement Script

Moves the car forward for 4 seconds, stops, then moves backward for 4 seconds.

Usage:
python3 demo_movement.py
"""

import time
import logging
from lib.movement import CarControl

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def main():
    """Main demo function"""
    logger.info("Starting car movement demo")

    try:
        # Initialize car control
        car = CarControl()
        logger.info("Car control initialized successfully")

        # Move forward for 4 seconds
        logger.info("Moving forward for 4 seconds...")
        if car.forward():
            logger.info("Forward movement started")
        else:
            logger.error("Failed to start forward movement")
            return

        if car.set_speed(50):  # 50% speed
            logger.info("Speed set to 50%")
        else:
            logger.error("Failed to set speed")
            return

        time.sleep(4)

        # Stop
        logger.info("Stopping car...")
        if car.stop():
            logger.info("Car stopped")
        else:
            logger.error("Failed to stop car")
            return

        time.sleep(2)  # Pause for 2 seconds

        # Move backward for 4 seconds
        logger.info("Moving backward for 4 seconds...")
        if car.backward():
            logger.info("Backward movement started")
        else:
            logger.error("Failed to start backward movement")
            return

        if car.set_speed(50):  # 50% speed
            logger.info("Speed set to 50%")
        else:
            logger.error("Failed to set speed")
            return

        time.sleep(4)

        # Final stop
        logger.info("Stopping car...")
        if car.stop():
            logger.info("Car stopped - demo complete")
        else:
            logger.error("Failed to stop car")

    except KeyboardInterrupt:
        logger.info("Demo interrupted by user")
        try:
            car.stop()
        except:
            pass
    except Exception as e:
        logger.error(f"Demo failed: {e}")
        try:
            car.stop()
        except:
            pass

if __name__ == '__main__':
    main()
