#!/usr/bin/env python3
# -*- coding: utf-8 -*-
########################################################################
# Filename    : lidar_random_navigation.py
# Description : Random navigation using LiDAR-like sensor to avoid obstacles and go fast
# Author      : Generated by AI Assistant
# Modification: 2026/01/06
########################################################################
"""
Random LiDAR Navigation Script

Uses ultrasonic sensor (acting as LiDAR) to detect obstacles, navigate randomly,
and move at high speed.

Usage:
python3 lidar_random_navigation.py
"""

import time
import random
import logging
from lib.movement import CarControl

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Constants
OBSTACLE_DISTANCE = 20.0  # cm - distance to consider as obstacle
FAST_SPEED = 80  # % - high speed for navigation
TURN_DURATION = 1.0  # seconds - how long to turn
STRAIGHT_DURATION = 2.0  # seconds - how long to go straight between checks

def main():
    """Main navigation function"""
    logger.info("Starting random LiDAR navigation")

    try:
        # Initialize car control
        car = CarControl()
        logger.info("Car control initialized successfully")

        # Center steering and camera
        car.center_steering()
        car.camera_center()
        time.sleep(1)

        # Start forward movement at high speed
        if not car.forward():
            logger.error("Failed to start forward movement")
            return

        if not car.set_speed(FAST_SPEED):
            logger.error(f"Failed to set speed to {FAST_SPEED}%")
            return

        logger.info(f"Moving at {FAST_SPEED}% speed, navigating randomly with LiDAR")

        while True:
            # Check distance using ultrasonic (acting as LiDAR)
            distance = car.get_distance()
            logger.info(f"LiDAR distance: {distance:.2f} cm")

            if distance < OBSTACLE_DISTANCE and distance > 0:
                # Obstacle detected, stop and turn randomly
                logger.warning(f"Obstacle detected at {distance:.2f} cm, turning randomly")
                car.stop()

                # Randomly choose to turn left or right
                turn_direction = random.choice(['left', 'right'])
                if turn_direction == 'left':
                    car.turn_left(45)
                else:
                    car.turn_right(45)

                time.sleep(TURN_DURATION)

                # Center steering and resume forward
                car.center_steering()
                time.sleep(0.5)

                # Resume forward at high speed
                car.forward()
                car.set_speed(FAST_SPEED)

            else:
                # No obstacle, continue straight
                logger.info("Path clear, continuing forward")
                time.sleep(STRAIGHT_DURATION)

    except KeyboardInterrupt:
        logger.info("Navigation interrupted by user")
        try:
            car.stop()
            car.center_steering()
            car.camera_center()
        except:
            pass
    except Exception as e:
        logger.error(f"Navigation failed: {e}")
        try:
            car.stop()
            car.center_steering()
            car.camera_center()
        except:
            pass

if __name__ == '__main__':
    main()
