#!/usr/bin/env python3
# -*- coding: utf-8 -*-
########################################################################
# Filename    : camera.py
# Description : Flask camera streaming server
# Author      : Generated by AI Assistant
# Modification: 2026/01/04
########################################################################
"""
Flask Camera Streaming Server

Provides MJPEG camera streaming on a dedicated port.

Requirements:
- flask
- picamera2
- opencv-python

Installation:
pip3 install flask picamera2 opencv-python

Usage:
python3 camera.py
Then visit http://raspberrypi:5000 in browser
"""

from flask import Flask, Response
from picamera2 import Picamera2
import cv2
import threading
import time
from typing import Optional, Generator

app = Flask(__name__)

class CameraStream:
    """
    Handles camera capture and frame generation for streaming.
    """

    def __init__(self) -> None:
        self.camera: Picamera2 = Picamera2()
        self.camera.configure(self.camera.create_video_configuration(main={"size": (640, 480)}))
        self.camera.start()
        self.frame: Optional[cv2.Mat] = None
        self.thread: threading.Thread = threading.Thread(target=self._update, args=())
        self.thread.daemon = True
        self.thread.start()

    def _update(self) -> None:
        """Continuously capture frames in background thread."""
        while True:
            frame = self.camera.capture_array()
            self.frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
            time.sleep(0.1)

    def get_frame(self) -> Optional[bytes]:
        """
        Get the latest frame as JPEG bytes.

        Returns:
            JPEG encoded frame bytes or None if no frame available
        """
        if self.frame is not None:
            ret, jpeg = cv2.imencode('.jpg', self.frame)
            return jpeg.tobytes()
        return None

    def __del__(self) -> None:
        """Stop the camera when object is destroyed."""
        self.camera.stop()

camera_stream = CameraStream()

def gen() -> Generator[bytes, None, None]:
    """Generate MJPEG frames."""
    while True:
        frame = camera_stream.get_frame()
        if frame:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        time.sleep(0.1)

@app.route('/')
def video_feed() -> Response:
    """MJPEG video feed endpoint."""
    return Response(gen(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
